# Generated by rust2rpm 26
%bcond_without check

%global crate wayscriber
%global cargo_install_lib 0

Name:           wayscriber
Version:        0.9.9
Release:        1%{?dist}
Summary:        ZoomIt-like real-time screen annotation tool for Wayland

License:        MIT
URL:            https://github.com/devmobasa/wayscriber
Source:         %{url}/archive/refs/tags/v%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  make
BuildRequires:  pkgconf-pkg-config
BuildRequires:  cairo-devel
BuildRequires:  wayland-devel
BuildRequires:  pango-devel
BuildRequires:  libxkbcommon-devel
BuildRequires:  cairo-gobject-devel

%global _description %{expand:
Wayscriber is a ZoomIt-like real-time screen annotation tool for Linux/Wayland.
It provides a live overlay for drawing, annotating with zoom capabilities,
hiding text, and capturing screenshots.}

%description %{_description}

%prep
%autosetup -n wayscriber-%{version} -p1
cargo vendor
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/wayscriber
%{_bindir}/dump_config_schema

%changelog
%autochangelog
