# Generated by rust2rpm 26
# Tests require a display server (GPU-based renderer)
%bcond_with check

%global crate inlyne
%global cargo_install_lib 0

Name:           inlyne
Version:        0.5.0
Release:        1%{?dist}
Summary:        GPU powered, browserless markdown viewer

License:        MIT
URL:            https://github.com/Inlyne-Project/inlyne
Source0:        %{url}/archive/refs/tags/v%{version}.tar.gz
Source1:        fix-metrics-rust186.py

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  fontconfig-devel
BuildRequires:  libxkbcommon-devel
BuildRequires:  wayland-devel
BuildRequires:  libX11-devel
BuildRequires:  vulkan-loader-devel
BuildRequires:  oniguruma-devel

%global _description %{expand:
A GPU powered yet browserless tool to help you quickly view markdown files in
the blink of an eye.}

%description %{_description}

%package bash-completion
BuildArch:      noarch
Summary:        Bash completion files for %{name}
Provides:       %{name}-bash-completion = %{version}-%{release}

Requires:       bash-completion
Requires:       %{name} = %{version}-%{release}

%description bash-completion
This package installs Bash completion files for %{name}

%package fish-completion
BuildArch:      noarch
Summary:        Fish completion files for %{name}
Provides:       %{name}-fish-completion = %{version}-%{release}

Requires:       fish
Requires:       %{name} = %{version}-%{release}

%description fish-completion
This package installs Fish completion files for %{name}

%package zsh-completion
BuildArch:      noarch
Summary:        Zsh completion files for %{name}
Provides:       %{name}-zsh-completion = %{version}-%{release}

Requires:       zsh
Requires:       %{name} = %{version}-%{release}

%description zsh-completion
This package installs Zsh completion files for %{name}

%prep
%autosetup -n %{crate}-%{version} -p1
cargo vendor
# Fix metrics crate for Rust 1.86+ (rust-lang/rust#141402)
python3 %{SOURCE1}
%cargo_prep -v vendor

%build
export RUSTONIG_SYSTEM_LIBONIG=1
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
export RUSTONIG_SYSTEM_LIBONIG=1
%cargo_install

install -Dpm644 completions/inlyne.bash %{buildroot}%{bash_completions_dir}/inlyne
install -Dpm644 completions/inlyne.fish %{buildroot}%{fish_completions_dir}/inlyne.fish
install -Dpm644 completions/_inlyne %{buildroot}%{zsh_completions_dir}/_inlyne

%if %{with check}
%check
export RUSTONIG_SYSTEM_LIBONIG=1
%cargo_test -- --skip test_redraw --skip integration
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/inlyne

%files bash-completion
%{bash_completions_dir}/inlyne

%files fish-completion
%{fish_completions_dir}/inlyne.fish

%files zsh-completion
%{zsh_completions_dir}/_inlyne

%changelog
%autochangelog
