# Generated by rust2rpm 26
%bcond_without check

%global crate dotter

Name:           dotter
Version:        0.13.4
Release:        1%{?dist}
Summary:        A dotfile manager and templater written in Rust

License:        Unlicense
URL:            https://github.com/SuperCuber/dotter
Source:         %{url}/archive/v%{version}/%{crate}-%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
Dotter is a dotfile manager and templater. It allows you to manage your
dotfiles across multiple machines with ease, supporting templating with
Handlebars syntax for machine-specific configuration.}

%description %{_description}

%package bash-completion
BuildArch:      noarch
Summary:        Bash completion files for %{name}
Provides:       %{name}-bash-completion = %{version}-%{release}

Requires:       bash-completion
Requires:       %{name} = %{version}-%{release}

%description bash-completion
This package installs Bash completion files for %{name}

%package fish-completion
BuildArch:      noarch
Summary:        Fish completion files for %{name}
Provides:       %{name}-fish-completion = %{version}-%{release}

Requires:       fish
Requires:       %{name} = %{version}-%{release}

%description fish-completion
This package installs Fish completion files for %{name}

%package zsh-completion
BuildArch:      noarch
Summary:        Zsh completion files for %{name}
Provides:       %{name}-zsh-completion = %{version}-%{release}

Requires:       zsh
Requires:       %{name} = %{version}-%{release}

%description zsh-completion
This package installs Zsh completion files for %{name}

%prep
%autosetup -n %{crate}-%{version} -p1
cargo vendor
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

# Generate shell completions
%{buildroot}%{_bindir}/dotter gen-completions --shell bash > dotter.bash
%{buildroot}%{_bindir}/dotter gen-completions --shell fish > dotter.fish
%{buildroot}%{_bindir}/dotter gen-completions --shell zsh > _dotter

install -Dpm644 dotter.bash %{buildroot}%{bash_completions_dir}/dotter
install -Dpm644 dotter.fish %{buildroot}%{fish_completions_dir}/dotter.fish
install -Dpm644 _dotter %{buildroot}%{zsh_completions_dir}/_dotter

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE.md
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc README.md
%{_bindir}/dotter

%files bash-completion
%{bash_completions_dir}/dotter

%files fish-completion
%{fish_completions_dir}/dotter.fish

%files zsh-completion
%{zsh_completions_dir}/_dotter

%changelog
%autochangelog
